<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-WorkerService-0e3722fd-5d75-4c8c-8f2f-d49d1b39570c</UserSecretsId>
        <RootNamespace>DietiEstate.WorkerService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6"/>
    </ItemGroup>
</Project>
