<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-WorkerService-0e3722fd-5d75-4c8c-8f2f-d49d1b39570c</UserSecretsId>
        <RootNamespace>DietiEstate.WorkerService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>
</Project>
